# Generated by Django 4.2.7 on 2024-02-02 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.DecimalField(decimal_places=1, max_digits=2)),
                ('type', models.TextField()),
                ('note', models.TextField()),
                ('date_administered', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_administered', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
