# Generated by Django 5.0.1 on 2024-02-07 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_rename_author_insulin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reading', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note', models.TextField()),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
