# Generated by Django 5.0.1 on 2024-02-07 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_glucose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='insulin',
            old_name='type',
            new_name='insulin_type',
        ),
        migrations.CreateModel(
            name='InsulinChanged',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insulin_type', models.TextField()),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
