# Generated by Django 5.0.1 on 2024-02-08 01:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminders',
            new_name='Reminder',
        ),
    ]
