# Generated by Django 5.0.1 on 2024-02-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_rename_reminders_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='time',
            new_name='date_due',
        ),
    ]
