# Generated by Django 5.0.1 on 2024-02-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_rename_time_reminder_date_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='total_card_intake',
            new_name='total_carb_intake',
        ),
    ]
