# Generated by Django 5.0.1 on 2024-02-09 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_rename_total_card_intake_meal_total_carb_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='insulin',
            name='dose',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.CreateModel(
            name='Cgm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor', models.TextField(blank=True, null=True)),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
