# Generated by Django 5.0.1 on 2024-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_insulin_dose_cgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgm',
            name='sensor_life',
            field=models.TextField(blank=True, null=True),
        ),
    ]
