# Generated by Django 5.0.1 on 2024-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_cgm_sensor_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgm',
            name='sensor_life',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
