# Generated by Django 5.0.1 on 2024-02-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_rename_sensor_life_cgm_sensor_life_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgm',
            name='sensor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cgm',
            name='sensor_life_in_days',
            field=models.IntegerField(),
        ),
    ]
